/**
 * SIH PS 44 - Application and Database Enums
 * Strictly adhering to MASTER PROMPT definitions
 */

export enum StudentSkillLevel {
  BEGINNER = 'BEGINNER',
  INTERMEDIATE = 'INTERMEDIATE',
  ADVANCED = 'ADVANCED',
  EXPERT = 'EXPERT',
}

export enum SkillGapPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum SkillGapStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
}

export enum ApplicationStatus {
  APPLIED = 'APPLIED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  SHORTLISTED = 'SHORTLISTED',
  INTERVIEW = 'INTERVIEW',
  SELECTED = 'SELECTED',
  REJECTED = 'REJECTED',
}

export enum AssessmentQuestionType {
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  SINGLE_CHOICE = 'SINGLE_CHOICE',
  CODING = 'CODING',
  SHORT_ANSWER = 'SHORT_ANSWER',
}

export enum AssessmentAttemptStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  ABANDONED = 'ABANDONED',
}

export enum OpportunityStatus {
  DRAFT = 'DRAFT',
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
}

export enum OpportunityType {
  JOB = 'JOB',
  INTERNSHIP = 'INTERNSHIP',
  PROJECT = 'PROJECT',
  LEARNING_PROGRAM = 'LEARNING_PROGRAM',
  FACULTY_OPPORTUNITY = 'FACULTY_OPPORTUNITY',
  FDP = 'FDP',
  RESEARCH_OPPORTUNITY = 'RESEARCH_OPPORTUNITY',
  CONSULTANCY_OPPORTUNITY = 'CONSULTANCY_OPPORTUNITY',
}

export enum WorkplaceType {
  ON_SITE = 'ON_SITE',
  REMOTE = 'REMOTE',
  HYBRID = 'HYBRID',
}

export enum EmploymentType {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  CONTRACT = 'CONTRACT',
  INTERNSHIP = 'INTERNSHIP',
}

export enum CollaborationType {
  WORKSHOP = 'WORKSHOP',
  GUEST_LECTURE = 'GUEST_LECTURE',
  INDUSTRIAL_TRAINING = 'INDUSTRIAL_TRAINING',
  LIVE_PROJECT = 'LIVE_PROJECT',
}

export enum CollaborationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum StudentAffiliationStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum MentorshipStatus {
  REQUESTED = 'REQUESTED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  COMPLETED = 'COMPLETED',
}

export enum DocumentAccessLevel {
  PUBLIC = 'PUBLIC',
  PRIVATE = 'PRIVATE',
  RESTRICTED = 'RESTRICTED',
}

export enum NotificationType {
  APPLICATION_SUBMITTED = 'APPLICATION_SUBMITTED',
  SHORTLISTED = 'SHORTLISTED',
  REJECTED = 'REJECTED',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
  STUDENT_SELECTED = 'STUDENT_SELECTED',
  NEW_OPPORTUNITY = 'NEW_OPPORTUNITY',
  SKILL_GAP_DETECTED = 'SKILL_GAP_DETECTED',
  LEARNING_RECOMMENDATION = 'LEARNING_RECOMMENDATION',
  MENTORSHIP_ACCEPTED = 'MENTORSHIP_ACCEPTED',
}

export enum AuditAction {
  LOGIN = 'LOGIN',
  OPPORTUNITY_CREATED = 'OPPORTUNITY_CREATED',
  APPLICATION_STATUS_CHANGED = 'APPLICATION_STATUS_CHANGED',
  DOCUMENT_ACCESSED = 'DOCUMENT_ACCESSED',
  PLACEMENT_CHANGED = 'PLACEMENT_CHANGED',
  ROLE_SENSITIVE_ACTION = 'ROLE_SENSITIVE_ACTION',
}

export enum DegreeLevel {
  UNDERGRADUATE = 'UNDERGRADUATE',
  POSTGRADUATE = 'POSTGRADUATE',
  DIPLOMA = 'DIPLOMA',
  DOCTORATE = 'DOCTORATE',
  CERTIFICATE = 'CERTIFICATE',
}

export enum EnrollmentStatus {
  ENROLLED = 'ENROLLED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  DROPPED = 'DROPPED',
  SUSPENDED = 'SUSPENDED',
}


